ERROR - 2025-07-18 05:07:28 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'cukkuboo' in C:\xampp\htdocs\Cukkuboo\cukkuboo-php\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'cukkuboo', 3306, '', 0)
#1 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\system\BaseModel.php(717): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\app\Models\UserModel.php(96): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\app\Libraries\AuthService.php(27): App\Models\UserModel->findUserByToken('eyJ0eXAiOiJKV1Q...')
#8 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\app\Controllers\Usersub.php(450): App\Libraries\AuthService->getAuthenticatedUser('Bearer eyJ0eXAi...')
#9 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\system\CodeIgniter.php(933): App\Controllers\Usersub->getExpiredSubscriptions()
#10 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usersub))
#11 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'cukkuboo' in C:\xampp\htdocs\Cukkuboo\cukkuboo-php\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\system\BaseModel.php(717): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\app\Models\UserModel.php(96): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\app\Libraries\AuthService.php(27): App\Models\UserModel->findUserByToken('eyJ0eXAiOiJKV1Q...')
#7 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\app\Controllers\Usersub.php(450): App\Libraries\AuthService->getAuthenticatedUser('Bearer eyJ0eXAi...')
#8 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\system\CodeIgniter.php(933): App\Controllers\Usersub->getExpiredSubscriptions()
#9 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usersub))
#10 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
ERROR - 2025-07-18 05:45:27 --> mysqli_sql_exception: Unknown column 'user_id' in 'field list' in C:\xampp\htdocs\Cukkuboo\cukkuboo-php\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `su...', 0)
#1 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `su...')
#2 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `su...')
#3 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `su...', Array, false)
#4 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\system\BaseModel.php(843): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\app\Controllers\Support.php(72): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\system\CodeIgniter.php(933): App\Controllers\Support->submitIssue()
#9 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Support))
#10 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\Cukkuboo\cukkuboo-php\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-07-18 05:45:27 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'user_id' in 'field list'
[Method: POST, Route: support/submit]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `support_issues` (`user_id`, `email`, `phone`, `issue_type`, `description`, `screenshot`, `created_by`, `created_on`) VALUES (:user_id:, :email:, :phone:, :issue_type:, :description:, :screenshot:, :created_by:, :created_on:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Support.php(72): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Support->submitIssue()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Support))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-07-18 05:45:27 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'user_id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `support_issues` (`user_id`, `email`, `phone`, `issue_type`, `description`, `screenshot`, `created_by`, `created_on`) VALUES (\'30\', \'ifra@gmail.com\', \'1234565435\', \'bug\', \'bugs in controller\', \'\', \'30\', \'2025-07-18 05:45:27\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `support_issues` (`user_id`, `email`, `phone`, `issue_type`, `description`, `screenshot`, `created_by`, `created_on`) VALUES (\'30\', \'ifra@gmail.com\', \'1234565435\', \'bug\', \'bugs in controller\', \'\', \'30\', \'2025-07-18 05:45:27\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `support_issues` (`user_id`, `email`, `phone`, `issue_type`, `description`, `screenshot`, `created_by`, `created_on`) VALUES (:user_id:, :email:, :phone:, :issue_type:, :description:, :screenshot:, :created_by:, :created_on:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Support.php(72): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Support->submitIssue()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Support))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-07-18 05:45:27 --> [Caused by] mysqli_sql_exception: Unknown column 'user_id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `support_issues` (`user_id`, `email`, `phone`, `issue_type`, `description`, `screenshot`, `created_by`, `created_on`) VALUES (\'30\', \'ifra@gmail.com\', \'1234565435\', \'bug\', \'bugs in controller\', \'\', \'30\', \'2025-07-18 05:45:27\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `support_issues` (`user_id`, `email`, `phone`, `issue_type`, `description`, `screenshot`, `created_by`, `created_on`) VALUES (\'30\', \'ifra@gmail.com\', \'1234565435\', \'bug\', \'bugs in controller\', \'\', \'30\', \'2025-07-18 05:45:27\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `support_issues` (`user_id`, `email`, `phone`, `issue_type`, `description`, `screenshot`, `created_by`, `created_on`) VALUES (\'30\', \'ifra@gmail.com\', \'1234565435\', \'bug\', \'bugs in controller\', \'\', \'30\', \'2025-07-18 05:45:27\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `support_issues` (`user_id`, `email`, `phone`, `issue_type`, `description`, `screenshot`, `created_by`, `created_on`) VALUES (:user_id:, :email:, :phone:, :issue_type:, :description:, :screenshot:, :created_by:, :created_on:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(843): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Support.php(72): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Support->submitIssue()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Support))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
